import json, subprocess, sys, re
from pathlib import Path
import urllib.request

API = "http://127.0.0.1:8000/v1/chat/completions"
MODEL = "/workspace/models/deepseek-coder-v2-lite"

PROMPT = (
    "Generate a Java class named MultiplyOneToTen with a main method. "
    "The program should compute the multiplication of numbers from 1 to 10 "
    "(1*2*3*...*10) using a loop, store the result in a long variable, "
    "and print the result. Output ONLY valid Java code. No markdown."
)

payload = {
    "model": MODEL,
    "messages": [
        {"role": "system", "content": "Return ONLY raw Java code. No markdown, no explanations."},
        {"role": "user", "content": PROMPT}
    ],
    "temperature": 0.2,
    "max_tokens": 400
}

req = urllib.request.Request(
    API,
    data=json.dumps(payload).encode("utf-8"),
    headers={"Content-Type": "application/json"},
    method="POST"
)

with urllib.request.urlopen(req, timeout=300) as r:
    data = json.loads(r.read().decode("utf-8"))

code = data["choices"][0]["message"]["content"].strip()

# safety cleanup
code = re.sub(r"^\s*```(?:java)?\s*", "", code, flags=re.I)
code = re.sub(r"\s*```\s*$", "", code)
code = code.rstrip().rstrip(".")

src = Path("/workspace/selenium-poc/MultiplyOneToTen.java")
src.write_text(code + "\n", encoding="utf-8")

print("[OK] Java file generated by DeepSeek:")
print(src)
